[package]
name = "chunk-store"
description = "Environment persistence abstraction and database adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
chunk-contract = { path = "../chunk-contract" }

[lints]
workspace = true
