// Generated by chunk codegen. Edits are replaced on the next generation.
import schema from "../../server/schema/index.ts";
import type { Document } from "../sdk/documents.ts";
import { defineFunctions } from "../sdk/functions.ts";
import type { QueryContext as SchemaQueryContext, MutationContext as SchemaMutationContext } from "../sdk/functions.ts";
import type { Id as TableId } from "../sdk/validators.ts";

export { v, unset } from "../sdk/index.ts";
export type {
  Validator,
  ObjectValidator,
  OptionalValidator,
  Shape,
  Infer,
  InferObject,
  PlayerIdentity,
  Destination,
  AdmissionResult,
  ServerStatus,
  PlayerId,
  SessionId,
  JsonValue,
  AsyncContext,
  ActionContext,
  FunctionDefinition,
  FunctionBuilder,
  FunctionReference,
  Selection,
} from "../sdk/index.ts";

type Tables = typeof schema.tables;
export type QueryContext = SchemaQueryContext<Tables>;
export type MutationContext = SchemaMutationContext<Tables>;
export type Doc<N extends keyof Tables & string> = Document<Tables, N>;
export type Id<N extends keyof Tables & string> = TableId<N>;

export const { action, internalAction, query, mutation, internalQuery, internalMutation } = defineFunctions(schema);
