// Generated by chunk codegen. Edits are replaced on the next generation.
import schema from "../../server/schema/index.ts";
import type { Document } from "../sdk/documents.ts";
import { defineFunctions } from "../sdk/functions.ts";
import type { QueryContext as SchemaQueryContext, MutationContext as SchemaMutationContext } from "../sdk/functions.ts";
import type { Id as TableId } from "../sdk/validators.ts";

export {
  v,
  unset,
  createHook,
  command,
  commandRoute,
  commandArg,
  sessionMethod,
  defineDestination,
} from "../sdk/index.ts";
export type {
  SessionMethodDeclaration,
  SessionMethodReference,
  DestinationDefinition,
  DestinationOptions,
  Validator,
  ObjectValidator,
  OptionalValidator,
  Shape,
  Infer,
  InferObject,
  PlayerIdentity,
  Destination,
  AdmissionResult,
  ServerStatus,
  PlayerId,
  SessionId,
  JsonValue,
  CommandContext,
  CommandEffectReceipt,
  CommandPlayer,
  CommandSession,
  CommandRouting,
  CommandArgument,
  CommandArguments,
  CommandShape,
  CommandRoute,
  CommandDefinition,
  CommandPermission,
  CommandSuggestions,
  SuggestionQuery,
  HookContexts,
  HookResults,
  HookEvent,
  HookOptions,
  HookDefinition,
  AsyncContext,
  ActionContext,
  HttpRequest,
  HttpOutcome,
  FunctionDefinition,
  FunctionBuilder,
  FunctionReference,
  Selection,
} from "../sdk/index.ts";

type Tables = typeof schema.tables;
export type QueryContext = SchemaQueryContext<Tables>;
export type MutationContext = SchemaMutationContext<Tables>;
export type Doc<N extends keyof Tables & string> = Document<Tables, N>;
export type Id<N extends keyof Tables & string> = TableId<N>;

export const { action, internalAction, query, mutation, internalQuery, internalMutation } = defineFunctions(schema);

export type { JobId, Scheduler } from "../sdk/jobs.ts";
