use std::fmt::Write;

use chunk_contract::FunctionKind;

use super::java::{Function, Namespace};

pub(super) fn source(package: &str, root: &Namespace) -> String {
    format!(
        "// Generated by chunk-codegen.\npackage {package}\n\nimport dev.chunkzero.backend.CoroutineBackend\nimport dev.chunkzero.backend.api.*\nimport dev.chunkzero.backend.client.OperationId\nimport dev.chunkzero.backend.client.WatchState\nimport kotlinx.coroutines.flow.Flow\n\n/** Borrows an owned CoroutineBackend; the adapter controls call and watch lifetimes. */\nclass CoroutineBackendClient(private val _backend: CoroutineBackend) {{\n{}\n}}\n",
        body(root, "    ")
    )
}

fn body(namespace: &Namespace, indent: &str) -> String {
    let mut declarations = Vec::new();
    for child in &namespace.children {
        let ty = &child.type_name;
        declarations.push(format!("{indent}val {} = {ty}(_backend)", child.member_name));
    }
    declarations.extend(namespace.functions.iter().map(|function| methods(function, indent)));
    for child in &namespace.children {
        declarations.push(format!(
            "{indent}class {} internal constructor(private val _backend: CoroutineBackend) {{\n{}\n{indent}}}",
            child.type_name,
            body(child, &format!("{indent}    "))
        ));
    }
    declarations.join("\n\n")
}

fn methods(function: &Function, indent: &str) -> String {
    let name = &function.name;
    let args = function.arguments.kotlin_type();
    let result = function.result.kotlin_type();
    let reference = &function.reference;
    match function.kind {
        FunctionKind::Action => {
            let mut methods =
                format!("{indent}suspend fun {name}(args: {args}): {result} = _backend.perform({reference}, args)");
            if function.empty_arguments {
                write!(methods, "\n\n{indent}suspend fun {name}(): {result} = {name}({args}())")
                    .expect("write to String");
            }
            methods
        }
        FunctionKind::Mutation => {
            let mut methods = format!(
                "{indent}suspend fun {name}(args: {args}, operation: OperationId): {result} =\n{indent}    _backend.mutate({reference}, args, operation)"
            );
            if function.empty_arguments {
                write!(
                    methods,
                    "\n\n{indent}suspend fun {name}(operation: OperationId): {result} = {name}({args}(), operation)"
                )
                .expect("write to String");
            }
            methods
        }
        FunctionKind::Query => {
            let watch = function.watch_name.as_ref().expect("query watch name");
            let mut methods = format!(
                "{indent}suspend fun {name}(args: {args}): {result} = _backend.query({reference}, args)\n\n{indent}fun {watch}(args: {args}): Flow<WatchState<{result}>> = _backend.watch({reference}, args)"
            );
            if function.empty_arguments {
                write!(methods,
                    "\n\n{indent}suspend fun {name}(): {result} = {name}({args}())\n\n{indent}fun {watch}(): Flow<WatchState<{result}>> = {watch}({args}())"
                ).expect("write to String");
            }
            methods
        }
    }
}
