use std::collections::BTreeMap;

use chunk_contract::{Field, FunctionKind, Schema, Visibility};
use serde_json::Value;

use super::{BackendMetadata, quote};

pub(super) fn generate(contract: &BackendMetadata) -> String {
    let mut api = serde_json::json!({});
    let mut internal = serde_json::json!({});
    for (path, function) in &contract.functions {
        let kind = match function.kind {
            FunctionKind::Query => "query",
            FunctionKind::Mutation => "mutation",
            FunctionKind::Action => "action",
        };
        insert(
            if function.visibility == Visibility::Public { &mut api } else { &mut internal },
            path,
            format!(
                "{{ path: {}, kind: {}, arguments: apiValidator({}), result: apiValidator({}) }}",
                quote(path),
                quote(kind),
                schema(&function.arguments),
                schema(&function.result)
            ),
        );
    }
    let documents = contract
        .tables
        .iter()
        .map(|(name, table)| format!("{}: v.document({}, {})", quote(name), quote(name), fields(&table.fields)))
        .collect::<Vec<_>>();
    format!(
        "// Generated by chunk-codegen.\nimport {{v,apiValidator}} from '#chunk/schema';\nimport type {{Infer}} from '#chunk/schema';\nexport type {{Id,PlayerId,SessionId}} from '#chunk/schema';\nfunction shape<T>(fields: T): T {{ return fields; }}\nexport const api = {} as const;\nexport const internal = {} as const;\nexport const documents = {{{}}} as const;\nexport type Doc<T extends keyof typeof documents> = Infer<(typeof documents)[T]>;\n",
        tree(&api),
        tree(&internal),
        documents.join(",\n")
    )
}

pub(super) fn fields(fields: &BTreeMap<String, Field>) -> String {
    format!(
        "shape({{{}}})",
        fields
            .iter()
            .map(|(name, field)| {
                let validator = schema(&field.schema);
                format!(
                    "{}: {}",
                    quote(name),
                    if field.optional { format!("v.optional({validator})") } else { validator }
                )
            })
            .collect::<Vec<_>>()
            .join(",")
    )
}

pub(super) fn schema(value: &Schema) -> String {
    match value {
        Schema::Null => "v.null()".into(),
        Schema::Boolean => "v.boolean()".into(),
        Schema::Number => "v.number()".into(),
        Schema::Integer => "v.integer()".into(),
        Schema::String => "v.string()".into(),
        Schema::Id { table } => format!("v.id({})", quote(table)),
        Schema::Player => "v.player()".into(),
        Schema::Session => "v.session()".into(),
        Schema::Literal { value } => format!("v.literal({value})"),
        Schema::Enum { values } => format!("v.enum({})", values.iter().map(quote).collect::<Vec<_>>().join(",")),
        Schema::Nullable { value } => format!("v.nullable({})", schema(value)),
        Schema::Array { items } => format!("v.array({})", schema(items)),
        Schema::Object { fields: declarations } => {
            if let Some(Field { schema: Schema::Id { table }, .. }) = declarations.get("_id") {
                let mut rest = declarations.clone();
                rest.remove("_id");
                format!("v.document({}, {})", quote(table), fields(&rest))
            } else {
                format!("v.object({})", fields(declarations))
            }
        }
        Schema::Union { variants } => format!(
            "v.union({{{}}})",
            variants
                .iter()
                .map(|(name, variant)| format!("{}:{}", quote(name), schema(variant)))
                .collect::<Vec<_>>()
                .join(",")
        ),
    }
}

pub(super) fn tree(node: &Value) -> String {
    match node {
        Value::String(value) => value.clone(),
        Value::Object(fields) => format!(
            "{{{}}}",
            fields
                .iter()
                .map(|(name, value)| format!("[{}]:{}", quote(name), tree(value)))
                .collect::<Vec<_>>()
                .join(",\n")
        ),
        _ => unreachable!("reference tree"),
    }
}

pub(super) fn insert(api: &mut Value, path: &str, entry: String) {
    let mut node = api;
    let segments: Vec<_> = path.split('/').collect();
    for segment in &segments[..segments.len() - 1] {
        node =
            node.as_object_mut().expect("validated namespace").entry(*segment).or_insert_with(|| serde_json::json!({}));
    }
    node.as_object_mut()
        .expect("validated namespace")
        .insert(segments.last().expect("validated function path").to_string(), Value::String(entry));
}
