use std::{collections::BTreeMap, fmt::Write};

use chunk_contract::{DatabaseSchema, Field, MigrationKind, MigrationTable, Schema};

use super::journal::Journal;
use crate::quote;

/// Field renames per table, from the old name to the new one.
pub type Renames = BTreeMap<String, BTreeMap<String, String>>;

/// `.chunk/generated/migrations.ts`: each expand migration's row types, from its own snapshots.
pub(crate) fn declarations(journal: &Journal) -> String {
    let mut source = String::from(
        "// Generated by chunk from server/migrations. Edits are replaced on the next generation.\nimport type { Id, PlayerId, SessionId } from \"../sdk/validators.ts\";\ndeclare module \"../sdk/migrations.ts\" {\n  interface Migrations {\n",
    );
    for (index, entry) in journal.entries.iter().enumerate() {
        if entry.kind != MigrationKind::Expand {
            continue;
        }
        let (previous, current) = (journal.previous(index), &journal.snapshots[index]);
        writeln!(source, "    {}: {{", quote(&entry.id)).expect("string write");
        for (table, change) in super::diff::changes(&previous, current) {
            let (old, row) = (&previous[&table], &current[&table]);
            let pick = |fields: &BTreeMap<String, Field>, names: &[String]| {
                fields.iter().filter(|(name, _)| names.contains(name)).map(|(n, f)| (n.clone(), f.clone())).collect()
            };
            writeln!(
                source,
                "      {}: {{\n        old: {};\n        row: {};\n        added: {};\n        removed: {};\n      }};",
                quote(&table),
                document(&table, &old.fields),
                document(&table, &row.fields),
                object(&pick(&row.fields, &change.added)),
                object(&pick(&old.fields, &change.removed)),
            )
            .expect("string write");
        }
        source.push_str("    };\n");
    }
    source.push_str("  }\n}\nexport {};\n");
    source
}

/// A new migration's source: renamed fields are mapped both ways, and other new required fields are left to fill in.
pub(crate) fn migration(
    id: &str,
    schema: &DatabaseSchema,
    changes: &BTreeMap<String, MigrationTable>,
    renames: &Renames,
) -> String {
    let mut source =
        format!("import {{ defineMigration }} from \"#chunk\";\n\nexport default defineMigration({}, {{\n", quote(id));
    let none = BTreeMap::new();
    for (table, change) in changes {
        let renames = renames.get(table).unwrap_or(&none);
        let mut to = Vec::new();
        let mut missing = Vec::new();
        for field in &change.added {
            if let Some((old, _)) = renames.iter().find(|(_, new)| *new == field) {
                to.push(format!("{field}: old.{old}"));
            } else if !schema[table].fields[field].optional {
                missing.push(field.as_str());
            }
        }
        let back: Vec<_> = change
            .removed
            .iter()
            .map(|field| renames.get(field).map(|new| format!("{field}: row.{new}")))
            .collect::<Option<_>>()
            .unwrap_or_default();
        writeln!(source, "  {table}: {{").expect("string write");
        if !missing.is_empty() {
            writeln!(source, "    // TODO: return {} from the old row.", missing.join(", ")).expect("string write");
        }
        writeln!(source, "    to: (old) => ({{ {} }}),", to.join(", ")).expect("string write");
        if !back.is_empty() || change.removed.is_empty() {
            writeln!(source, "    back: (row) => ({{ {} }}),", back.join(", ")).expect("string write");
        }
        source.push_str("  },\n");
    }
    source.push_str("});\n");
    source
}

fn document(table: &str, fields: &BTreeMap<String, Field>) -> String {
    let mut object = object(fields);
    object.insert_str(1, &format!(" readonly _id: Id<{}>;", quote(table)));
    object
}

fn object(fields: &BTreeMap<String, Field>) -> String {
    let fields: Vec<_> = fields
        .iter()
        .map(|(name, field)| {
            format!("{}{}: {}", quote(name), if field.optional { "?" } else { "" }, render(&field.schema))
        })
        .collect();
    if fields.is_empty() { "{}".into() } else { format!("{{ {} }}", fields.join("; ")) }
}

fn render(schema: &Schema) -> String {
    match schema {
        Schema::Null => "null".into(),
        Schema::Boolean => "boolean".into(),
        Schema::Number | Schema::Integer => "number".into(),
        Schema::String => "string".into(),
        Schema::Id { table } => format!("Id<{}>", quote(table)),
        Schema::Player => "PlayerId".into(),
        Schema::Session => "SessionId".into(),
        Schema::Literal { value } => value.to_string(),
        Schema::Enum { values } => values.iter().map(quote).collect::<Vec<_>>().join(" | "),
        Schema::Nullable { value } => format!("({} | null)", render(value)),
        Schema::Array { items } => format!("({})[]", render(items)),
        Schema::Object { fields } => object(fields),
        Schema::Union { variants } => variants
            .iter()
            .map(|(name, variant)| {
                let mut variant = render(variant);
                variant.insert_str(1, &format!(" type: {};", quote(name)));
                variant
            })
            .collect::<Vec<_>>()
            .join(" | "),
    }
}
