use std::fmt::Write;

use chunk_contract::FunctionKind;

use super::{Function, Namespace};

pub(super) fn source(package: &str, root: &Namespace) -> String {
    format!(
        "// Generated by chunk-codegen.\npackage {package};\nimport com.chunkzero.chunk.backend.api.*;\nimport com.chunkzero.chunk.backend.client.*;\nimport java.util.*;\nimport java.util.concurrent.CompletableFuture;\nimport java.util.function.Consumer;\npublic final class BackendClient {{\n{}\n}}\n",
        body(root, "BackendClient", "public")
    )
}

fn body(namespace: &Namespace, name: &str, constructor: &str) -> String {
    let mut declarations = vec!["private final BackendSession session;".into()];
    let mut initialize = vec!["this.session = Objects.requireNonNull(session);".into()];
    for (index, child) in namespace.children.iter().enumerate() {
        let ty = &child.type_name;
        let member = &child.member_name;
        declarations.push(format!(
            "private final {ty} group{index};\npublic {ty} {member}() {{ return group{index}; }}\npublic static final class {ty} {{\n{}\n}}",
            body(child, ty, "private")
        ));
        initialize.push(format!("this.group{index} = new {ty}(session);"));
    }
    declarations.push(format!("{constructor} {name}(BackendSession session) {{ {} }}", initialize.join(" ")));
    declarations.extend(namespace.functions.iter().map(methods));
    declarations.join("\n")
}

fn methods(function: &Function) -> String {
    let name = &function.name;
    let args = &function.arguments.ty;
    let result = &function.result.ty;
    let reference = &function.reference;
    match function.kind {
        FunctionKind::Action => {
            let mut methods = format!(
                "public CompletableFuture<{result}> {name}({args} args) {{ return session.perform({reference}, args); }}"
            );
            if function.empty_arguments {
                write!(methods, "\npublic CompletableFuture<{result}> {name}() {{ return {name}(new {args}()); }}")
                    .expect("write to String");
            }
            methods
        }
        FunctionKind::Mutation => {
            let mut methods = format!(
                "public CompletableFuture<{result}> {name}({args} args, OperationId operation) {{ return session.mutate({reference}, args, operation); }}"
            );
            if function.empty_arguments {
                write!(methods,
                    "\npublic CompletableFuture<{result}> {name}(OperationId operation) {{ return {name}(new {args}(), operation); }}"
                ).expect("write to String");
            }
            methods
        }
        FunctionKind::Query => {
            let watch = function.watch_name.as_ref().expect("query watch name");
            let mut methods = format!(
                "public CompletableFuture<{result}> {name}({args} args) {{ return session.query({reference}, args); }}\npublic AutoCloseable {watch}({args} args, Consumer<WatchState<{result}>> observer) {{ return session.watch({reference}, args, observer); }}"
            );
            if function.empty_arguments {
                write!(methods,
                    "\npublic CompletableFuture<{result}> {name}() {{ return {name}(new {args}()); }}\npublic AutoCloseable {watch}(Consumer<WatchState<{result}>> observer) {{ return {watch}(new {args}(), observer); }}"
                ).expect("write to String");
            }
            methods
        }
    }
}
