use std::{collections::BTreeMap, io};

use chunk_contract::{SessionConfigurationDeclaration, SessionConfigurations};
use serde_json::json;

use super::{container, names, schema, support::SupportClass, validate_literals};

pub(super) fn sources(
    configurations: Option<&SessionConfigurations>,
    package: &str,
) -> io::Result<BTreeMap<String, String>> {
    let mut apps: BTreeMap<&str, Vec<&SessionConfigurationDeclaration>> = BTreeMap::new();
    for config in configurations.into_iter().flat_map(|value| &value.configurations) {
        apps.entry(&config.app).or_default().push(config);
    }
    let mut class = SupportClass::new("SessionConfigs")?;
    let mut metadata = Vec::new();
    let mut files = BTreeMap::new();
    for (app, mut configurations) in apps {
        let mut app_scope = class.app(app)?;
        let provider_name = format!("{}SessionProviders", app_scope.path.last().expect("app scope path"));
        let mut provider_scope = schema::Scope::new(vec![provider_name.clone()]);
        configurations.sort_by_key(|configuration| &configuration.session);
        for configuration in configurations {
            let session = &configuration.session;
            validate_literals(&configuration.configuration)?;
            let session_name = names::type_name(session, &app_scope.path);
            let mut scope = app_scope.child(&session_name, session)?;
            scope.declare("TYPE", "configuration codec")?;
            let config = class.generator.schema(&mut scope, &configuration.configuration, "Config", session)?;
            scope.declarations.push(format!(
                "public static final JsonType<{}> TYPE = {};",
                config.ty,
                config.json_type()
            ));
            app_scope.declarations.push(container(&session_name, &scope.declarations.join("\n")));
            let provider = names::type_name(session, &provider_scope.path);
            provider_scope.declare(&provider, session)?;
            provider_scope.declarations.push(format!(
                "public interface {provider} extends com.chunkzero.chunk.runtime.ConfiguredSessionProvider<{}> {{\n@Override default JsonType<{}> configurationType() {{ return {}.TYPE; }}\n}}",
                config.ty, config.ty, scope.path.join(".")
            ));
            metadata.push(json!({
                "app": app, "session": session, "configuration": configuration.configuration,
                "interface": format!("{package}.{provider_name}.{provider}"),
                "binary_interface": format!("{package}.{provider_name}${provider}"),
            }));
        }
        class.finish_app(&app_scope);
        files.insert(
            format!("java-session/{app}/{}/{provider_name}.java", package.replace('.', "/")),
            format!(
                "// Generated by chunk-codegen.\npackage {package};\nimport com.chunkzero.chunk.backend.api.JsonType;\npublic final class {provider_name} {{\nprivate {provider_name}() {{}}\n{}\n}}\n",
                provider_scope.declarations.join("\n")
            ),
        );
    }
    let (path, source) = class.source(package)?;
    files.insert(path, source);
    files.insert(
        "session-configurations.json".into(),
        serde_json::to_string(&json!({"version":1,"configurations":metadata}))?,
    );
    Ok(files)
}
