use std::{collections::BTreeMap, io};

use chunk_contract::{SessionConfigurationDeclaration, SessionConfigurations};
use serde_json::json;

use super::{container, names, quote, schema, validate_literals};

pub(super) fn sources(
    configurations: Option<&SessionConfigurations>,
    package: &str,
) -> io::Result<BTreeMap<String, String>> {
    let mut apps: BTreeMap<&str, Vec<&SessionConfigurationDeclaration>> = BTreeMap::new();
    for config in configurations.into_iter().flat_map(|value| &value.configurations) {
        apps.entry(&config.app).or_default().push(config);
    }
    let mut generator = schema::Generator { root: "SessionConfigs".into(), ..Default::default() };
    let mut root = schema::Scope::new(vec!["SessionConfigs".into()]);
    root.declare("Ids", "table IDs")?;
    let mut metadata = Vec::new();
    let mut files = BTreeMap::new();
    for (app, mut configurations) in apps {
        let app_name = names::type_name(app, &root.path);
        root.declare(&app_name, app)?;
        let provider_name = format!("{app_name}SessionProviders");
        let mut provider_scope = schema::Scope::new(vec![provider_name.clone()]);
        let mut app_scope = schema::Scope::new(vec!["SessionConfigs".into(), app_name.clone()]);
        configurations.sort_by_key(|configuration| &configuration.session);
        for configuration in configurations {
            let session = &configuration.session;
            validate_literals(&configuration.configuration)?;
            let session_name = names::type_name(session, &app_scope.path);
            app_scope.declare(&session_name, session)?;
            let mut path = app_scope.path.clone();
            path.push(session_name.clone());
            let mut scope = schema::Scope::new(path);
            scope.declare("TYPE", "configuration codec")?;
            let config = generator.schema(&mut scope, &configuration.configuration, "Config", session)?;
            scope.declarations.push(format!(
                "public static final JsonType<{}> TYPE = {};",
                config.ty,
                config.json_type()
            ));
            app_scope.declarations.push(container(&session_name, &scope.declarations.join("\n")));
            let provider = names::type_name(session, &provider_scope.path);
            provider_scope.declare(&provider, session)?;
            provider_scope.declarations.push(format!(
                "public interface {provider} extends dev.chunkzero.runtime.ConfiguredSessionProvider<{}> {{\n@Override default JsonType<{}> configurationType() {{ return {}.TYPE; }}\n}}",
                config.ty, config.ty, scope.path.join(".")
            ));
            metadata.push(json!({
                "app": app, "session": session, "configuration": configuration.configuration,
                "interface": format!("{package}.{provider_name}.{provider}"),
                "binary_interface": format!("{package}.{provider_name}${provider}"),
            }));
        }
        root.declarations.push(container(&app_name, &app_scope.declarations.join("\n")));
        files.insert(
            format!("java-session/{app}/{}/{provider_name}.java", package.replace('.', "/")),
            format!(
                "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.JsonType;\npublic final class {provider_name} {{\nprivate {provider_name}() {{}}\n{}\n}}\n",
                provider_scope.declarations.join("\n")
            ),
        );
    }
    let mut ids = Vec::new();
    let mut id_names = names::Names::default();
    for (table, name) in generator.ids {
        id_names.insert("SessionConfigs.Ids", &name, &table)?;
        ids.push(format!("public record {name}(@JsonValue String value) {{ @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public {name} {{ BackendValues.tableId({}, value); }} }}", quote(&table)));
    }
    root.declarations.push(container("Ids", &ids.join("\n")));
    files.insert(
        format!("java/{}/SessionConfigs.java", package.replace('.', "/")),
        format!(
            "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.*;\nimport com.fasterxml.jackson.annotation.*;\nimport tools.jackson.core.type.TypeReference;\nimport tools.jackson.databind.annotation.JsonTypeResolver;\nimport java.util.*;\npublic final class SessionConfigs {{\nprivate SessionConfigs() {{}}\n{}\n}}\n",
            root.declarations.join("\n")
        ),
    );
    files.insert(
        "session-configurations.json".into(),
        serde_json::to_string(&json!({"version":1,"configurations":metadata}))?,
    );
    Ok(files)
}
