use std::{collections::BTreeMap, io};

use chunk_contract::{Destination, DestinationManifest};

use super::{container, names, quote, schema};

/// `Destinations`, each app's declared destinations as `Destination` constants, as `#chunk/apps` exposes them.
pub(super) fn sources(manifest: Option<&DestinationManifest>, package: &str) -> io::Result<(String, String)> {
    let mut apps: BTreeMap<&str, Vec<(&str, &Destination)>> = BTreeMap::new();
    for (id, policy) in manifest.into_iter().flat_map(|manifest| &manifest.entries) {
        if let Some((app, name)) = id.strip_prefix("apps/").and_then(|path| path.split_once("/destinations/")) {
            apps.entry(app).or_default().push((name, &policy.destination));
        }
    }
    let mut root = schema::Scope::new(vec!["Destinations".into()]);
    for (app, destinations) in apps {
        let name = names::type_name(app, &root.path);
        let mut scope = root.child(&name, app)?;
        for (destination, value) in destinations {
            let member = names::member_name(destination);
            scope.declare(&member, destination)?;
            scope.declarations.push(format!(
                "public static final Destination {member} = new Destination({}, {}, {});",
                quote(&value.key),
                quote(&value.session_type),
                quote(&value.machine_profile)
            ));
        }
        root.declarations.push(container(&name, &scope.declarations.join("\n")));
    }
    Ok((
        format!("java/{}/Destinations.java", package.replace('.', "/")),
        format!(
            "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.Destination;\npublic final class Destinations {{\nprivate Destinations() {{}}\n{}\n}}\n",
            root.declarations.join("\n")
        ),
    ))
}
