use std::{collections::BTreeMap, io};

use chunk_contract::{SessionMethodDeclaration, SessionMethods};
use serde_json::json;

use super::{container, names, quote, schema, validate_literals};

type Sessions<'a> = BTreeMap<&'a str, BTreeMap<&'a str, Vec<&'a SessionMethodDeclaration>>>;

pub(super) fn sources(methods: Option<&SessionMethods>, package: &str) -> io::Result<BTreeMap<String, String>> {
    let mut groups = Sessions::new();
    for method in methods.into_iter().flat_map(|value| &value.methods) {
        groups.entry(&method.app).or_default().entry(&method.session).or_default().push(method);
    }
    let mut generator = schema::Generator { root: "SessionMethods".into(), ..Default::default() };
    let mut root = schema::Scope::new(vec!["SessionMethods".into()]);
    root.declare("Ids", "table IDs")?;
    let mut metadata = Vec::new();
    for (app, sessions) in groups {
        let app_name = names::type_name(app, &root.path);
        root.declare(&app_name, app)?;
        let mut app_scope = schema::Scope::new(vec!["SessionMethods".into(), app_name.clone()]);
        for (session, mut declarations) in sessions {
            let session_name = names::type_name(session, &app_scope.path);
            app_scope.declare(&session_name, session)?;
            let mut path = app_scope.path.clone();
            path.push(session_name.clone());
            let mut scope = schema::Scope::new(path);
            declarations.sort_by_key(|method| &method.name);
            for method in declarations {
                validate_literals(&method.arguments)?;
                validate_literals(&method.result)?;
                let name = names::type_name(&method.name, &scope.path);
                scope.declare(&name, &method.name)?;
                let mut path = scope.path.clone();
                path.push(name.clone());
                let mut signature = schema::Scope::new(path);
                signature.declare("REF", "method reference")?;
                let arguments = generator.schema(&mut signature, &method.arguments, "Args", &method.name)?;
                let result = generator.schema(&mut signature, &method.result, "Result", &method.name)?;
                let function_name = names::member_name(&method.name);
                signature.declare(&function_name, "implementation method")?;
                scope.declarations.push(format!(
                    "public interface {name} {{\n{} {}({} args);\nSessionMethodRef<{}, {}> REF = new SessionMethodRef<>({}, {}, {}, {}, {});\n{}\n}}",
                    result.ty, function_name, arguments.ty,
                    arguments.ty, result.ty, quote(app), quote(session), quote(&method.name),
                    arguments.json_type(), result.json_type(), signature.declarations.join("\n")
                ));
                metadata.push(json!({
                    "app": app, "session": session, "name": method.name,
                    "interface": format!("{package}.{}", signature.path.join(".")),
                    "binary_interface": format!("{package}.{}", signature.path.join("$")),
                    "function": function_name,
                    "arguments": method.arguments, "result": method.result,
                }));
            }
            app_scope.declarations.push(container(&session_name, &scope.declarations.join("\n")));
        }
        root.declarations.push(container(&app_name, &app_scope.declarations.join("\n")));
    }
    let mut ids = Vec::new();
    let mut id_names = names::Names::default();
    for (table, name) in generator.ids {
        id_names.insert("SessionMethods.Ids", &name, &table)?;
        ids.push(format!("public record {name}(@JsonValue String value) {{ @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public {name} {{ BackendValues.tableId({}, value); }} }}", quote(&table)));
    }
    root.declarations.push(container("Ids", &ids.join("\n")));
    let source = format!(
        "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.*;\nimport com.fasterxml.jackson.annotation.*;\nimport tools.jackson.core.type.TypeReference;\nimport tools.jackson.databind.annotation.JsonTypeResolver;\nimport java.util.*;\npublic final class SessionMethods {{\nprivate SessionMethods() {{}}\n{}\n}}\n",
        root.declarations.join("\n")
    );
    Ok(BTreeMap::from([
        (format!("java/{}/SessionMethods.java", package.replace('.', "/")), source),
        ("session-methods.json".into(), serde_json::to_string(&json!({"version": 1, "methods": metadata}))?),
    ]))
}
