use std::io;

use super::{container, names, quote, schema};

/// A generated `public final class` holding per-app nested containers plus a shared `Ids` container.
pub(super) struct SupportClass {
    name: &'static str,
    pub generator: schema::Generator,
    pub root: schema::Scope,
}

impl SupportClass {
    pub fn new(name: &'static str) -> io::Result<Self> {
        let mut root = schema::Scope::new(vec![name.into()]);
        root.declare("Ids", "table IDs")?;
        Ok(Self { name, generator: schema::Generator { root: name.into(), ..Default::default() }, root })
    }

    pub fn app(&mut self, app: &str) -> io::Result<schema::Scope> {
        let name = names::type_name(app, &self.root.path);
        self.root.child(&name, app)
    }

    pub fn finish_app(&mut self, scope: &schema::Scope) {
        let name = scope.path.last().expect("app scope path");
        self.root.declarations.push(container(name, &scope.declarations.join("\n")));
    }

    pub fn source(mut self, package: &str) -> io::Result<(String, String)> {
        let mut ids = Vec::new();
        let mut id_names = names::Names::default();
        for (table, name) in self.generator.ids {
            id_names.insert(&format!("{}.Ids", self.name), &name, &table)?;
            ids.push(format!("public record {name}(@JsonValue String value) {{ @JsonCreator(mode = JsonCreator.Mode.DELEGATING) public {name} {{ BackendValues.tableId({}, value); }} }}", quote(&table)));
        }
        self.root.declarations.push(container("Ids", &ids.join("\n")));
        let path = format!("java/{}/{}.java", package.replace('.', "/"), self.name);
        Ok((path, class_source(package, self.name, &self.root.declarations.join("\n"))))
    }
}

pub(super) fn class_source(package: &str, name: &str, body: &str) -> String {
    format!(
        "// Generated by chunk-codegen.\npackage {package};\nimport com.chunkzero.chunk.backend.api.*;\nimport com.fasterxml.jackson.annotation.*;\nimport tools.jackson.core.type.TypeReference;\nimport tools.jackson.databind.annotation.JsonTypeResolver;\nimport java.util.*;\npublic final class {name} {{\nprivate {name}() {{}}\n{body}\n}}\n"
    )
}
