use std::{collections::BTreeMap, fmt::Write, io};

use chunk_contract::EnvManifest;

use super::{java_constant, names, quote};

/// `Vars`, the project's `chunk.toml` variables as constants, which resolve as the backend's do for the environment
/// `CHUNK_ENVIRONMENT_NAME` names. Variables `[vars]` sets are `String`s, and those only some environments set are
/// `Optional<String>`s. Field initializers call only statically imported methods, which no field name can obscure.
pub(super) fn source(env: &EnvManifest, package: &str) -> io::Result<(String, String)> {
    // Every variable, with the environments that override it.
    let mut vars: BTreeMap<&str, Vec<(&str, &str)>> = env.vars.keys().map(|name| (name.as_str(), Vec::new())).collect();
    for (environment, overrides) in &env.environments {
        for (name, value) in overrides {
            vars.entry(name).or_default().push((environment, value));
        }
    }
    let mut names = names::Names::default();
    let mut fields = String::new();
    for (name, overrides) in vars {
        let default = env.vars.get(name).map(String::as_str);
        let field = names::field_name(name);
        names.insert("Vars", &field, name)?;
        if default.into_iter().chain(overrides.iter().map(|(_, value)| *value)).any(|value| !java_constant(value)) {
            return Err(io::Error::other(format!("variable {name} exceeds the Java string constant limit")));
        }
        let ty = if default.is_some() { "String" } else { "Optional<String>" };
        let value = |value: &str| if default.is_some() { quote(value) } else { format!("of({})", quote(value)) };
        let fallback = default.map_or_else(|| "empty()".to_owned(), value);
        write!(fields, "public static final {ty} {field} = ").expect("write to String");
        if overrides.is_empty() {
            writeln!(fields, "{fallback};").expect("write to String");
        } else {
            fields.push_str("switch (environment()) {\n");
            for (environment, overridden) in overrides {
                writeln!(fields, "case {} -> {};", quote(environment), value(overridden)).expect("write to String");
            }
            writeln!(fields, "default -> {fallback};\n}};").expect("write to String");
        }
    }
    Ok((
        format!("java/{}/Vars.java", package.replace('.', "/")),
        format!(
            "// Generated by chunk-codegen.\npackage {package};\nimport static java.lang.System.getenv;\nimport static java.util.Objects.requireNonNullElse;\nimport static java.util.Optional.empty;\nimport static java.util.Optional.of;\nimport java.util.Optional;\n/** chunk.toml's [vars], with [env.NAME.vars] applied for the environment CHUNK_ENVIRONMENT_NAME names. */\npublic final class Vars {{\nprivate Vars() {{}}\nprivate static String environment() {{ return requireNonNullElse(getenv(\"CHUNK_ENVIRONMENT_NAME\"), \"\"); }}\n{fields}}}\n"
        ),
    ))
}
