use std::{collections::BTreeMap, fmt::Write, io};

use chunk_contract::EnvManifest;

use super::{names, quote};

/// The most UTF-16 units one string literal holds: at up to three bytes each in modified UTF-8, its class-file constant
/// stays within the 65,535-byte limit.
const LITERAL_UNITS: usize = 21_845;

/// `Vars`, the project's `chunk.toml` variables as constants, which resolve as the backend's do for the environment
/// `CHUNK_ENVIRONMENT_NAME` names. Variables `[vars]` sets are `String`s, and those only some environments set are
/// `Optional<String>`s. Each field has its own initializer method, named after it with a `$` no imported method has,
/// so no single method outgrows the class-file limits, and methods call only statically imported methods, which no
/// field name can obscure.
pub(super) fn source(env: &EnvManifest, package: &str) -> io::Result<(String, String)> {
    // Every variable, with the environments that override it.
    let mut vars: BTreeMap<&str, Vec<(&str, &str)>> = env.vars.keys().map(|name| (name.as_str(), Vec::new())).collect();
    for (environment, overrides) in &env.environments {
        for (name, value) in overrides {
            vars.entry(name).or_default().push((environment, value));
        }
    }
    let mut names = names::Names::default();
    let mut members = String::new();
    for (name, overrides) in vars {
        let default = env.vars.get(name).map(String::as_str);
        let field = names::field_name(name);
        names.insert("Vars", &field, name)?;
        let ty = if default.is_some() { "String" } else { "Optional<String>" };
        let value = |value: &str| if default.is_some() { literal(value) } else { format!("of({})", literal(value)) };
        let fallback = default.map_or_else(|| "empty()".to_owned(), value);
        writeln!(members, "public static final {ty} {field} = {field}$();\nprivate static {ty} {field}$() {{")
            .expect("write to String");
        if overrides.is_empty() {
            writeln!(members, "return {fallback};").expect("write to String");
        } else {
            members.push_str("return switch (environment()) {\n");
            for (environment, overridden) in overrides {
                writeln!(members, "case {} -> {};", quote(environment), value(overridden)).expect("write to String");
            }
            writeln!(members, "default -> {fallback};\n}};").expect("write to String");
        }
        members.push_str("}\n");
    }
    Ok((
        format!("java/{}/Vars.java", package.replace('.', "/")),
        format!(
            "// Generated by chunk-codegen.\npackage {package};\nimport static java.lang.String.join;\nimport static java.lang.System.getenv;\nimport static java.util.Objects.requireNonNullElse;\nimport static java.util.Optional.empty;\nimport static java.util.Optional.of;\nimport java.util.Optional;\n/** chunk.toml's [vars], with [env.NAME.vars] applied for the environment CHUNK_ENVIRONMENT_NAME names. */\npublic final class Vars {{\nprivate Vars() {{}}\nprivate static String environment() {{ return requireNonNullElse(getenv(\"CHUNK_ENVIRONMENT_NAME\"), \"\"); }}\n{members}}}\n"
        ),
    ))
}

/// `value` as a Java expression: one string literal, or literals of at most [`LITERAL_UNITS`] each, never splitting a
/// surrogate pair, joined at run time so that javac can't fold them back into one oversized constant.
fn literal(value: &str) -> String {
    let mut chunks = vec![String::new()];
    let mut units = 0;
    for character in value.chars() {
        if units + character.len_utf16() > LITERAL_UNITS {
            chunks.push(String::new());
            units = 0;
        }
        units += character.len_utf16();
        chunks.last_mut().expect("a chunk").push(character);
    }
    if chunks.len() == 1 {
        return quote(value);
    }
    let chunks: Vec<_> = chunks.iter().map(quote).collect();
    format!("join(\"\", {})", chunks.join(", "))
}
