use std::{
    collections::{BTreeMap, BTreeSet},
    io,
};

use super::{container, names, quote, schema};

/// Fully qualified, since an app's class may share its simple name.
const WORLD: &str = "dev.chunkzero.backend.api.WorldAsset";

/// `Worlds`, each app's declared worlds as `WorldAsset` constants, such as `Worlds.Arena.KOTH`.
pub(super) fn source(worlds: &BTreeMap<String, BTreeSet<String>>, package: &str) -> io::Result<(String, String)> {
    let mut root = schema::Scope::new(vec!["Worlds".into()]);
    for (app, worlds) in worlds {
        let name = names::type_name(app, &root.path);
        let mut scope = root.child(&name, app)?;
        for world in worlds {
            let member = constant(world);
            scope.declare(&member, world)?;
            scope.declarations.push(format!(
                "public static final {WORLD} {member} = new {WORLD}({}, {});",
                quote(app),
                quote(world)
            ));
        }
        root.declarations.push(container(&name, &scope.declarations.join("\n")));
    }
    Ok((
        format!("java/{}/Worlds.java", package.replace('.', "/")),
        format!(
            "// Generated by chunk-codegen.\npackage {package};\npublic final class Worlds {{\nprivate Worlds() {{}}\n{}\n}}\n",
            root.declarations.join("\n")
        ),
    ))
}

/// `koth` as `KOTH` and `lobbyMap` as `LOBBY_MAP`; `_`, which Java reserves, as `__`.
fn constant(name: &str) -> String {
    let mut result = String::new();
    let mut previous = b'_';
    for byte in name.bytes() {
        if byte.is_ascii_uppercase() && (previous.is_ascii_lowercase() || previous.is_ascii_digit()) {
            result.push('_');
        }
        result.push(char::from(byte.to_ascii_uppercase()));
        previous = byte;
    }
    if result == "_" { "__".into() } else { result }
}
