#!/usr/bin/env python3
"""Regenerate licenses/v8.txt from the license files of the V8 build linked in through the `v8` crate.

The crate on crates.io omits every LICENSE file, so they are read from the matching rusty_v8 tag and its
submodules. Run it again whenever Cargo.lock moves the `v8` crate to another version.
"""

import configparser
from pathlib import Path
import re
import subprocess
import tempfile
import tomllib

RUSTY_V8 = "https://github.com/denoland/rusty_v8"
# Components compiled into the prebuilt static library: (name, rusty_v8 submodule, directory in it).
COMPONENTS = [
    ("rusty_v8", "", ""),
    ("V8", "v8", ""),
    ("V8: glibc trigonometric functions", "v8", "third_party/glibc"),
    ("V8: inspector protocol", "v8", "third_party/inspector_protocol"),
    ("V8: rapidhash", "v8", "third_party/rapidhash-v8"),
    ("V8: SipHash", "v8", "third_party/siphash"),
    ("V8: UTF-8 decoder", "v8", "third_party/utf8-decoder"),
    ("V8: array sort builtins", "v8", "third_party/v8/builtins"),
    ("V8: fp16 code generation", "v8", "third_party/v8/codegen"),
    ("V8: Valgrind client API", "v8", "third_party/valgrind"),
    ("ICU", "third_party/icu", ""),
    ("Abseil", "third_party/abseil-cpp", ""),
    ("libc++", "third_party/libc++/src", ""),
    ("libc++abi", "third_party/libc++abi/src", ""),
    ("LLVM libc", "third_party/llvm-libc/src", ""),
    ("simdutf", "third_party/simdutf", ""),
    ("Highway", "third_party/highway/src", ""),
    ("fast_float", "third_party/fast_float/src", ""),
    ("Dragonbox", "third_party/dragonbox/src", ""),
    ("FP16", "third_party/fp16/src", ""),
]
LICENSE_FILE = re.compile(r"(LICEN[CS]E|COPYING|NOTICE)([.-][\w-]+)?", re.IGNORECASE)
RULE = "=" * 80


def git(repository, *args):
    return subprocess.run(["git", "-C", repository, *args], check=True, capture_output=True, text=True).stdout


def fetch(repository, remote, url, ref):
    git(repository, "remote", "add", remote, url)
    git(repository, "fetch", "--quiet", "--depth", "1", "--filter=blob:none", remote, ref)
    return git(repository, "rev-parse", "FETCH_HEAD^{commit}").strip()


def main():
    root = Path(__file__).resolve().parent.parent
    lock = tomllib.loads((root / "Cargo.lock").read_text())
    [version] = [package["version"] for package in lock["package"] if package["name"] == "v8"]
    tag = f"v{version}"
    sections = [
        f"Third-party notices for V8 as linked by the `v8` crate {version} ({RUSTY_V8}/tree/{tag}).",
        "Generated by scripts/v8-notices.py from the license files in each component's source.",
    ]
    with tempfile.TemporaryDirectory(prefix="v8-notices-") as repository:
        git(repository, "init", "--quiet", "--bare")
        tree = fetch(repository, "rusty_v8", RUSTY_V8, f"refs/tags/{tag}")
        modules = configparser.ConfigParser()
        modules.read_string(git(repository, "show", f"{tree}:.gitmodules"))
        commits = {"": (RUSTY_V8, tree)}
        for name, submodule, directory in COMPONENTS:
            if submodule not in commits:
                url = modules[f'submodule "{submodule}"']["url"]
                pinned = git(repository, "ls-tree", tree, submodule).split()[2]
                commits[submodule] = (url, fetch(repository, f"module{len(commits)}", url, pinned))
            url, commit = commits[submodule]
            prefix = f"{directory}/" if directory else ""
            files = [file for file in git(repository, "ls-tree", "--name-only", f"{commit}:{directory}").split()
                     if LICENSE_FILE.fullmatch(file) and not file.lower().endswith((".html", ".md"))]
            if not files:
                raise ValueError(f"No license file for {name} in {url} {directory}")
            for file in sorted(files):
                text = git(repository, "show", f"{commit}:{prefix}{file}").strip()
                sections.append(f"{RULE}\n{name}\nSource: {url} at {commit}, {prefix}{file}\n{RULE}\n\n{text}")
    (root / "licenses/v8.txt").write_text("\n\n".join(sections) + "\n")


if __name__ == "__main__":
    main()
