use std::{
    collections::{BTreeMap, BTreeSet},
    io,
    path::Path,
};

use chunk_contract::{Deployment, FunctionKind, Schema, Visibility};

use super::BackendMetadata;

mod java;
mod output;
mod typescript;

/// The explicitly selected developer-facing output. JVM sources share one Java model.
#[derive(Debug, Clone, Copy)]
pub enum GenerationTarget<'a> {
    Java { package: &'a str },
    TypeScript,
}

/// Generates only the selected client sources from a compiled contract.
/// Tracks owned files in the destination so package/target changes remove stale generated sources
/// without deleting handwritten files. Existing owned files must be unchanged before replacement.
/// # Errors
/// Rejects invalid contracts, unsupported literals, Java name collisions, output conflicts and filesystem failures.
pub fn generate(contract: &Path, output: &Path, target: GenerationTarget<'_>) -> io::Result<()> {
    let contract = read_contract(contract)?;
    let files = match target {
        GenerationTarget::Java { package } => java_sources(&contract, package)?,
        GenerationTarget::TypeScript => BTreeMap::from([("api.ts".into(), typescript::generate(&contract))]),
    };
    output::write(output, &files)
}

fn java_sources(contract: &BackendMetadata, package: &str) -> io::Result<BTreeMap<String, String>> {
    validate_package(package)?;
    let mut generator = java::Generator {
        declarations: Vec::new(),
        ids: BTreeSet::new(),
        codecs: BTreeSet::new(),
    };
    let mut references = Vec::new();
    let mut clients = Vec::new();
    let mut reference_names = BTreeSet::new();
    for (name, table) in &contract.tables {
        for field in table.fields.values() {
            validate_literals(&field.schema)?;
        }
        generator.ids.insert(name.clone());
        let mut fields = table.fields.clone();
        fields.insert(
            "_id".into(),
            chunk_contract::Field {
                schema: Schema::Id { table: name.clone() },
                optional: false,
            },
        );
        generator.schema(&Schema::Object { fields }, &format!("Doc${name}"));
    }
    for (path, function) in &contract.functions {
        if function.visibility != Visibility::Public {
            continue;
        }
        validate_literals(&function.arguments)?;
        validate_literals(&function.result)?;
        let name = if path.contains('/') {
            path.replace('/', "$")
        } else {
            java::identifier(path)
        };
        reference_names.insert(name.clone());
        let args = generator.schema(&function.arguments, &format!("Fn${name}$Args"));
        let result = generator.schema(&function.result, &format!("Fn${name}$Result"));
        let kind = match function.kind {
            FunctionKind::Query => "Query",
            FunctionKind::Mutation => "Mutation",
        };
        references.push(format!(
            "public static final {kind}Ref<{}, {}> {name} = new {kind}Ref<>({}, {}, {});",
            args.ty,
            result.ty,
            quote(path),
            args.codec,
            result.codec
        ));
        clients.push(java::client_method(&name, &args.ty, &result.ty, function.kind));
    }
    if let Some(name) = reference_names.intersection(&generator.codecs).next() {
        return Err(io::Error::other(format!(
            "Java function reference collides with generated codec: {name}"
        )));
    }
    let markers = generator
        .ids
        .iter()
        .map(|id| format!("public static final class Table${id} {{ private Table${id}() {{}} }}"))
        .collect::<Vec<_>>()
        .join("\n");
    let source = format!(
        "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.*;\nimport com.google.gson.*;\nimport java.util.*;\npublic final class BackendTypes {{\nprivate BackendTypes() {{}}\n{markers}\n{}\n{}\n}}\n",
        generator.declarations.join("\n"),
        references.join("\n")
    );
    let package_path = package.replace('.', "/");
    Ok(BTreeMap::from([
        (format!("java/{package_path}/BackendTypes.java"), source),
        (
            format!("java-client/{package_path}/BackendClient.java"),
            java::client_source(package, &clients),
        ),
    ]))
}

fn validate_package(package: &str) -> io::Result<()> {
    if package.is_empty()
        || package
            .split('.')
            .any(|part| java::identifier(part) != part || part.is_empty())
    {
        return Err(io::Error::other("invalid Java package"));
    }
    Ok(())
}

fn read_contract(contract: &Path) -> io::Result<BackendMetadata> {
    let contract: BackendMetadata =
        serde_json::from_slice(&super::read_limited(contract, 2 * 1024 * 1024)?).map_err(io::Error::other)?;
    Deployment {
        contract_version: contract.contract_version,
        runtime_profile: contract.runtime_profile,
        id: "codegen".into(),
        source: "// contract validation".into(),
        tables: contract.tables.clone(),
        functions: contract.functions.clone(),
    }
    .validate()
    .map_err(io::Error::other)?;
    Ok(contract)
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("string")
}

fn validate_literals(schema: &Schema) -> io::Result<()> {
    match schema {
        Schema::Literal { value } => {
            chunk_contract::validate_wire_value(value).map_err(io::Error::other)?;
            if let Some(value) = value.as_str() {
                // Class-file string constants use modified UTF-8 with a u16 byte length.
                let bytes: usize = value
                    .encode_utf16()
                    .map(|unit| match unit {
                        1..=0x7f => 1,
                        0..=0x7ff => 2,
                        _ => 3,
                    })
                    .sum();
                if bytes > usize::from(u16::MAX) {
                    return Err(io::Error::other("literal exceeds Java string constant limit"));
                }
            }
            Ok(())
        }
        Schema::Array { items } => validate_literals(items),
        Schema::Object { fields } => fields.values().try_for_each(|field| validate_literals(&field.schema)),
        Schema::Union { variants } => variants.iter().try_for_each(validate_literals),
        _ => Ok(()),
    }
}

#[cfg(test)]
mod tests;
