use std::{collections::BTreeSet, fs, io, path::Path};

use chunk_contract::{Deployment, FunctionKind, Schema, Visibility};
use serde_json::json;

use super::BackendMetadata;

mod java;
mod typescript;

/// Generates public TypeScript references and Java records/codecs from a compiled contract.
/// # Errors
/// Rejects invalid contracts, Java package names and filesystem failures.
pub fn generate(contract: &Path, output: &Path, package: &str) -> io::Result<()> {
    if package.is_empty()
        || package
            .split('.')
            .any(|part| java::identifier(part) != part || part.is_empty())
    {
        return Err(io::Error::other("invalid Java package"));
    }
    let contract: BackendMetadata =
        serde_json::from_slice(&super::read_limited(contract, 2 * 1024 * 1024)?).map_err(io::Error::other)?;
    Deployment {
        contract_version: contract.contract_version,
        runtime_profile: contract.runtime_profile,
        id: "codegen".into(),
        source: "// contract validation".into(),
        tables: contract.tables.clone(),
        functions: contract.functions.clone(),
    }
    .validate()
    .map_err(io::Error::other)?;
    let mut generator = java::Generator {
        declarations: Vec::new(),
        ids: BTreeSet::new(),
    };
    let mut references = Vec::new();
    let mut api = json!({});
    let mut documents = Vec::new();
    for (name, table) in &contract.tables {
        generator.ids.insert(name.clone());
        let mut fields = table.fields.clone();
        fields.insert(
            "_id".into(),
            chunk_contract::Field {
                schema: Schema::Id { table: name.clone() },
                optional: false,
            },
        );
        generator.schema(&Schema::Object { fields }, &format!("Doc${name}"));
        documents.push(format!(
            "{}: v.document({}, {})",
            quote(name),
            quote(name),
            typescript::fields(&table.fields)
        ));
    }
    for (path, function) in &contract.functions {
        if function.visibility != Visibility::Public {
            continue;
        }
        let name = if path.contains('/') {
            path.replace('/', "$")
        } else {
            java::identifier(path)
        };
        let args = generator.schema(&function.arguments, &format!("Fn${name}$Args"));
        let result = generator.schema(&function.result, &format!("Fn${name}$Result"));
        let kind = match function.kind {
            FunctionKind::Query => "Query",
            FunctionKind::Mutation => "Mutation",
        };
        references.push(format!(
            "public static final {kind}Ref<{}, {}> {name} = new {kind}Ref<>({}, {}, {});",
            args.ty,
            result.ty,
            quote(path),
            args.codec,
            result.codec
        ));
        let entry = format!(
            "{{ path: {}, kind: {}, arguments: {}, result: {} }}",
            quote(path),
            quote(&kind.to_lowercase()),
            typescript::schema(&function.arguments),
            typescript::schema(&function.result)
        );
        typescript::insert(&mut api, path, entry);
    }
    let markers = generator
        .ids
        .iter()
        .map(|id| format!("public static final class Table${id} {{ private Table${id}() {{}} }}"))
        .collect::<Vec<_>>()
        .join("\n");
    let source = format!(
        "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.*;\nimport com.google.gson.*;\nimport java.util.*;\npublic final class BackendTypes {{\nprivate BackendTypes() {{}}\n{markers}\n{}\n{}\n}}\n",
        generator.declarations.join("\n"),
        references.join("\n")
    );
    let typescript = format!(
        "// Generated by chunk-codegen.\nimport {{v}} from '@chunk/server';\nimport type {{Infer}} from '@chunk/server';\nexport type {{Id,PlayerId,SessionId}} from '@chunk/server';\nexport const api = {} as const;\nexport const documents = {{{}}} as const;\nexport type Doc<T extends keyof typeof documents> = Infer<(typeof documents)[T]>;\n",
        typescript::tree(&api),
        documents.join(",\n")
    );
    let java_directory = output.join("java").join(package.replace('.', "/"));
    fs::create_dir_all(&java_directory)?;
    fs::write(java_directory.join("BackendTypes.java"), source)?;
    fs::write(output.join("api.ts"), typescript)?;
    Ok(())
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("string")
}
