use std::{collections::BTreeSet, fs, io, path::Path};

use chunk_contract::{Deployment, FunctionKind, Schema, Visibility};
use serde_json::json;

use super::BackendMetadata;

mod java;
mod typescript;

/// Generates public TypeScript references and Java records/codecs from a compiled contract.
/// # Errors
/// Rejects invalid contracts, unsupported literals, Java name collisions and filesystem failures.
pub fn generate(contract: &Path, output: &Path, package: &str) -> io::Result<()> {
    validate_package(package)?;
    let contract = read_contract(contract)?;
    let mut generator = java::Generator {
        declarations: Vec::new(),
        ids: BTreeSet::new(),
        codecs: BTreeSet::new(),
    };
    let mut references = Vec::new();
    let mut clients = Vec::new();
    let mut reference_names = BTreeSet::new();
    let mut api = json!({});
    let mut documents = Vec::new();
    for (name, table) in &contract.tables {
        for field in table.fields.values() {
            validate_literals(&field.schema)?;
        }
        generator.ids.insert(name.clone());
        let mut fields = table.fields.clone();
        fields.insert(
            "_id".into(),
            chunk_contract::Field {
                schema: Schema::Id { table: name.clone() },
                optional: false,
            },
        );
        generator.schema(&Schema::Object { fields }, &format!("Doc${name}"));
        documents.push(format!(
            "{}: v.document({}, {})",
            quote(name),
            quote(name),
            typescript::fields(&table.fields)
        ));
    }
    for (path, function) in &contract.functions {
        if function.visibility != Visibility::Public {
            continue;
        }
        validate_literals(&function.arguments)?;
        validate_literals(&function.result)?;
        let name = if path.contains('/') {
            path.replace('/', "$")
        } else {
            java::identifier(path)
        };
        reference_names.insert(name.clone());
        let args = generator.schema(&function.arguments, &format!("Fn${name}$Args"));
        let result = generator.schema(&function.result, &format!("Fn${name}$Result"));
        let kind = match function.kind {
            FunctionKind::Query => "Query",
            FunctionKind::Mutation => "Mutation",
        };
        references.push(format!(
            "public static final {kind}Ref<{}, {}> {name} = new {kind}Ref<>({}, {}, {});",
            args.ty,
            result.ty,
            quote(path),
            args.codec,
            result.codec
        ));
        clients.push(java::client_method(&name, &args.ty, &result.ty, function.kind));
        let entry = format!(
            "{{ path: {}, kind: {}, arguments: {}, result: {} }}",
            quote(path),
            quote(&kind.to_lowercase()),
            typescript::schema(&function.arguments),
            typescript::schema(&function.result)
        );
        typescript::insert(&mut api, path, entry);
    }
    if let Some(name) = reference_names.intersection(&generator.codecs).next() {
        return Err(io::Error::other(format!(
            "Java function reference collides with generated codec: {name}"
        )));
    }
    let markers = generator
        .ids
        .iter()
        .map(|id| format!("public static final class Table${id} {{ private Table${id}() {{}} }}"))
        .collect::<Vec<_>>()
        .join("\n");
    let source = format!(
        "// Generated by chunk-codegen.\npackage {package};\nimport dev.chunkzero.backend.api.*;\nimport com.google.gson.*;\nimport java.util.*;\npublic final class BackendTypes {{\nprivate BackendTypes() {{}}\n{markers}\n{}\n{}\n}}\n",
        generator.declarations.join("\n"),
        references.join("\n")
    );
    let typescript = format!(
        "// Generated by chunk-codegen.\nimport {{v}} from '#chunk/schema';\nimport type {{Infer}} from '#chunk/schema';\nexport type {{Id,PlayerId,SessionId}} from '#chunk/schema';\nfunction shape<T>(fields: T): T {{ return fields; }}\nexport const api = {} as const;\nexport const documents = {{{}}} as const;\nexport type Doc<T extends keyof typeof documents> = Infer<(typeof documents)[T]>;\n",
        typescript::tree(&api),
        documents.join(",\n")
    );
    let java_directory = output.join("java").join(package.replace('.', "/"));
    fs::create_dir_all(&java_directory)?;
    fs::write(java_directory.join("BackendTypes.java"), source)?;
    fs::write(output.join("api.ts"), typescript)?;
    java::write_client(output, package, &clients)?;
    Ok(())
}

fn validate_package(package: &str) -> io::Result<()> {
    if package.is_empty()
        || package
            .split('.')
            .any(|part| java::identifier(part) != part || part.is_empty())
    {
        return Err(io::Error::other("invalid Java package"));
    }
    Ok(())
}

fn read_contract(contract: &Path) -> io::Result<BackendMetadata> {
    let contract: BackendMetadata =
        serde_json::from_slice(&super::read_limited(contract, 2 * 1024 * 1024)?).map_err(io::Error::other)?;
    Deployment {
        contract_version: contract.contract_version,
        runtime_profile: contract.runtime_profile,
        id: "codegen".into(),
        source: "// contract validation".into(),
        tables: contract.tables.clone(),
        functions: contract.functions.clone(),
    }
    .validate()
    .map_err(io::Error::other)?;
    Ok(contract)
}

fn quote(value: &str) -> String {
    serde_json::to_string(value).expect("string")
}

fn validate_literals(schema: &Schema) -> io::Result<()> {
    match schema {
        Schema::Literal { value } => {
            chunk_contract::validate_wire_value(value).map_err(io::Error::other)?;
            if let Some(value) = value.as_str() {
                // Class-file string constants use modified UTF-8 with a u16 byte length.
                let bytes: usize = value
                    .encode_utf16()
                    .map(|unit| match unit {
                        1..=0x7f => 1,
                        0..=0x7ff => 2,
                        _ => 3,
                    })
                    .sum();
                if bytes > usize::from(u16::MAX) {
                    return Err(io::Error::other("literal exceeds Java string constant limit"));
                }
            }
            Ok(())
        }
        Schema::Array { items } => validate_literals(items),
        Schema::Object { fields } => fields.values().try_for_each(|field| validate_literals(&field.schema)),
        Schema::Union { variants } => variants.iter().try_for_each(validate_literals),
        _ => Ok(()),
    }
}
